name: Half-year calendar
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.isocalendar.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_isocalendar: yes
