name: Half-year calendar
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.isocalendar.svg
         token: ${{ secrets.METRICS_TOKEN }}
         user: github
         base: header
         plugin_introduction: yes
         plugin_topics: yes
         plugin_topics_limit: 0
         plugin_topics_mode: icons
         plugin_topics_sort: stars
         plugin_isocalendar: yes
